democratic-csi:
  csiDriver:
    name: "org.democratic-csi.iscsi"
  storageClasses:
    - name: freenas-iscsi-csi
      defaultClass: false
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: ext4
  driver:
    config:
      driver: freenas-iscsi
      httpConnection:
        protocol: https
        port: 443
        username: root
        allowInsecure: true
      sshConnection:
        port: 22
      zfs:
        # the example below is useful for TrueNAS 12
        cli:
          sudoEnabled: true
          paths:
            zfs: /usr/local/sbin/zfs
            zpool: /usr/local/sbin/zpool
            sudo: /usr/local/bin/sudo
            chroot: /usr/sbin/chroot
        zvolEnableReservation: false
      iscsi:
        # leave empty to omit usage of -I with iscsiadm
        interface:
        namePrefix: csi-
        nameSuffix: "-cluster"
        extentInsecureTpc: true
        extentXenCompat: false
        extentDisablePhysicalBlocksize: true
        extentAvailThreshold: 0
  node:
    hostPID: true
    driver:
      extraEnv:
        - name: ISCSIADM_HOST_STRATEGY
          value: nsenter
        - name: ISCSIADM_HOST_PATH
          value: /usr/local/sbin/iscsiadm
      iscsiDirHostPath: /usr/local/etc/iscsi
      iscsiDirHostPathType: ""
