radarr:
    radarr:
        ingress:
            hosts:
                - host: in.lab
                  paths:
                  - path: /radarr
                    pathType: ImplementationSpecific
                - host: radarr.in.lab
                  paths:
                  - path: /
                    pathType: ImplementationSpecific
