kube-prometheus-stack:
    fullnameOverride: "kps"

    defaultRules:
      rules:
        etcd: false
        kubeScheduler: false

    alertmanager:
      ingress:
        hosts:
          - alertmanager.in.lab

    grafana:
        fullnameOverride: grafana
        adminPassword: prom-operator
        ingress:
          hosts:
            - grafana.in.lab
   
    prometheus-node-exporter:
        fullnameOverride: node-exporter

    prometheus:
        ingress:
          hosts:
            - prometheus.in.lab
        prometheusSpec:
            ruleSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false

    kubelet:
      enabled: true
      namespace: lama

    prometheusOperator:
        kubeletService:
          namespace: lama

    kube-state-metrics:
        fullnameOverride: kube-state-metrics

    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeControllerManager:
      enabled: false
