---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/version: {{ .Values.keycloak.operator.image.tag }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: keycloak-operator
