renovate:
  cronjob:
    # Every hour
    schedule: '0 * * * *'
    annotations: {}
    labels: {}
    concurrencyPolicy: ''
    failedJobsHistoryLimit: ''
    successfulJobsHistoryLimit: ''
    jobRestartPolicy: Never
  
  image:
    repository: ghcr.io/renovatebot/renovate
    tag: 40.62.1@sha256:ae81e55a741faea2befce0caeafc8ae0ef2de014a104d63a67df59c7d168b1e7
    pullPolicy: IfNotPresent
  
  existingSecret: 'renovate-env'

  env:
    LOG_LEVEL: "debug"

  renovate:
    # See https://docs.renovatebot.com/self-hosted-configuration
    config: |
      {
        "platform": "gitea",
        "autodiscover": false,
        "printConfig": true,
        "repositories": [repo-list-here]
      }
