{{- if eq .Values.templates.secrets "lab" }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: registry
    namespace: {{ .Release.Namespace }}
    annotations:
        helm.sh/hook: pre-install
data:
    config: czM6CiAgYXdzX3NpZ25hdHVyZV92ZXJzaW9uOiA0CiAgaG9zdDogczMuaW4ubGFiCiAgcmVnaW9uZW5kcG9pbnQ6ICJodHRwczovL3MzLmluLmxhYjo5MDAwIgogIHBhdGhfc3R5bGU6IHRydWUKICByZWdpb246IHVzLWVhc3QtMQogIGJ1Y2tldDogZ2l0bGFiLXJlZ2lzdHJ5CiAgYWNjZXNza2V5OiBsYWItYWNjZXNzLWtleQogIHNlY3JldGtleTogbGFiLXNlY3JldGUta2V5Cg== 
{{- end }}
