{{- if eq .Values.templates.secrets "lab" }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: object-storage
    namespace: {{ .Release.Namespace }}
    annotations:
        helm.sh/hook: pre-install
data:
    connection: cHJvdmlkZXI6IEFXUwojIFNwZWNpZnkgdGhlIHJlZ2lvbgpyZWdpb246IHVzLWVhc3QtMQojIFNwZWNpZnkgYWNjZXNzL3NlY3JldCBrZXlzCmF3c19hY2Nlc3Nfa2V5X2lkOiBsYWItYWNjZXNzLWtleQphd3Nfc2VjcmV0X2FjY2Vzc19rZXk6IGxhYi1zZWNyZXQta2V5CiMgVGhlIGJlbG93IHNldHRpbmdzIGFyZSBmb3IgUzMgY29tcGF0aWJsZSBlbmRwb2ludHMKIyAgIFNlZSBodHRwczovL2RvY3MuZ2l0bGFiLmNvbS9lZS9hZG1pbmlzdHJhdGlvbi9qb2JfYXJ0aWZhY3RzLmh0bWwjczMtY29tcGF0aWJsZS1jb25uZWN0aW9uLXNldHRpbmdzCmF3c19zaWduYXR1cmVfdmVyc2lvbjogNApob3N0OiBzMy5pbi5sYWIKZW5kcG9pbnQ6ICJodHRwczovL3MzLmluLmxhYjo5MDAwIgpwYXRoX3N0eWxlOiB0cnVlCg== 
{{- end }}
