synology-csi:
  fullnameOverride: synology-csi
  clientInfoSecret:
    create: true
  storageClasses:
    synology-csi-iscsi:
      isDefault: true
      reclaimPolicy: Delete
      parameters:
        fsType: 'ext4'
        formatOptions: "-E nodiscard"
        protocol: 'iscsi'
    delete:
      disabled: true
    retain:
      disabled: true
   #installCSIDriver: true
