---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: metallb-config
  name: metallb-config
data:
  config: |
      address-pools:
          - name: deafult
            protocol: layer2
            addresses:
            {{- range .Values.templates.addresses }}
                - {{ . | quote }}
            {{- end }}
