{{ if has "gollum-lab" .Values.istioTemplates.apps }}
{{ $appName := "gollum" }}
{{ $appDomain := "gollum.in.lab" }}
{{ $appNamespace := "gollum" }}
---
# Enable external auth
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ $appName }}-ext-auth
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: CUSTOM
  provider:
    name: "oauth-ext-authz"
  rules:
  - to:
    - operation:
        hosts: 
        - {{ $appDomain }}
---
# Require JWT
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: {{ $appName }}-jwt
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $appName }}
  jwtRules:
  #- issuer: {{ $.Values.istioTemplates.jwtIssuer }}
    # jwksUri: {{ $.Values.istioTemplates.jwtUri }}
  - issuer: "https://keycloak.in.lab/auth/realms/basic"
    jwksUri: "http://keycloak.in.lab/auth/realms/basic/protocol/openid-connect/certs" 
    fromHeaders:
    - name: authorization
      prefix: "Bearer "
    - name: x-forwarded-access-token
    #jwksUri: "https://keycloak.keycloak.svc.cluster.local:8443/auth/realms/basic/protocol/openid-connect/certs"
    #jwks: '{"keys":[{"kid":"6jKjEvevgqNqj4mgRJDm02f2gXZBqLofFUTW3E9FJxM","kty":"RSA","alg":"RS256","use":"sig","n":"j6wj2xhjwpITkKrBSRQvL4TAONHlJKgCdkiHwJgFPoufR9ydqWOTkFpZ7zYKnW_Inx3zRm7xMkuKoIDpCC1Dbsi72VDVnqMD_MFhIbqEiIrvzMceyGqS5A2dRQ6rlP9p15fm5ZBpZiFoe78iMH1xCTR1AsvTotSUaVZu6lN_bNZpKnWdujQvTV0kG0yq9pp5lwEKCyB5TMXKvKhF4RX7Ag12fRcvP-uAUc6LNd6EfbCaYsGrfgjLtBOoc7N33FTZ226w-V1OL7aofaRp3TohtP45d2dhOueZtFaFBjQTzmVh2woqbu3oDL5rGymcs1aBoeLQZ_ieuq7z8CEmuYiYzQ","e":"AQAB","x5c":["MIICmTCCAYECBgF6lfs8fDANBgkqhkiG9w0BAQsFADAQMQ4wDAYDVQQDDAViYXNpYzAeFw0yMTA3MTExNDMwMDhaFw0zMTA3MTExNDMxNDhaMBAxDjAMBgNVBAMMBWJhc2ljMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj6wj2xhjwpITkKrBSRQvL4TAONHlJKgCdkiHwJgFPoufR9ydqWOTkFpZ7zYKnW/Inx3zRm7xMkuKoIDpCC1Dbsi72VDVnqMD/MFhIbqEiIrvzMceyGqS5A2dRQ6rlP9p15fm5ZBpZiFoe78iMH1xCTR1AsvTotSUaVZu6lN/bNZpKnWdujQvTV0kG0yq9pp5lwEKCyB5TMXKvKhF4RX7Ag12fRcvP+uAUc6LNd6EfbCaYsGrfgjLtBOoc7N33FTZ226w+V1OL7aofaRp3TohtP45d2dhOueZtFaFBjQTzmVh2woqbu3oDL5rGymcs1aBoeLQZ/ieuq7z8CEmuYiYzQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQATDQXOhstamonBzlQIDYBnjSOmSLnDFBHCqexJ7EmADdeVyXK/61kM1sNiHPg7w25s0UXgmiY/Zrt1azXCoiHgZ3/AHEOWcJ1F05PjV0JpS1PvIRYGnR3QAFO/mlK8z/KGsNcP8dEwiG87niwcrLFYfhv1mHWqg6WAk96ZgG+d8ZyuJAgnZZ7NzwHQwum74suEGPak2IDFAIG3/CFwShLpUEKRrlTFHWBLqIspH92cx6fZ/VSDZqzXdQPyRDrWx37hBSn/LPPeM2m9I2TEXeSrITwCItxLsVC6wGR0UhhKxKuDXBc1qhYHe4J/su44b7Qs3FMXWfDPYYotzjB+U/cW"],"x5t":"ZCkCAsJF-uiLUUXfSog33ZEcFbg","x5t#S256":"rgDIImRcC0CrfhZFqpHL2_iZtb6TuQExtCpTJ4EPs38"}]}'
    #jwks: '{"realm":"basic","public_key":"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj6wj2xhjwpITkKrBSRQvL4TAONHlJKgCdkiHwJgFPoufR9ydqWOTkFpZ7zYKnW/Inx3zRm7xMkuKoIDpCC1Dbsi72VDVnqMD/MFhIbqEiIrvzMceyGqS5A2dRQ6rlP9p15fm5ZBpZiFoe78iMH1xCTR1AsvTotSUaVZu6lN/bNZpKnWdujQvTV0kG0yq9pp5lwEKCyB5TMXKvKhF4RX7Ag12fRcvP+uAUc6LNd6EfbCaYsGrfgjLtBOoc7N33FTZ226w+V1OL7aofaRp3TohtP45d2dhOueZtFaFBjQTzmVh2woqbu3oDL5rGymcs1aBoeLQZ/ieuq7z8CEmuYiYzQIDAQAB","token-service":"https://keycloak.in.lab/auth/realms/basic/protocol/openid-connect","account-service":"https://keycloak.in.lab/auth/realms/basic/account","tokens-not-before":0}'
    forwardOriginalToken: true
---
# Require explict authorization
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: allow-nothing
 namespace: {{ $appNamespace }}
spec:
  {}
---
# Allow from IngressGateway
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ $appName }}-ingress
  namespace: {{ $appNamespace }}
spec:
  action: ALLOW
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $appName }}
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"]
  - when:
      - key: request.auth.claims[email]
        values:
          - admin@example.com
---
# Create application gateway
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ $appName }}-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ $appDomain }}
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - {{ $appDomain }}
    tls:
      mode: SIMPLE
      credentialName: {{ .Values.istioTemplates.credentialName }}
---
# Create app Virtual Service
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $appName }}
spec:
  hosts:
  - {{ $appDomain }}
  gateways:
  - {{ $appName }}-gateway
  http:
  - route:
    - destination:
        port:
          number: 80
        host: {{ $appName }}.{{ $appNamespace }}.svc.cluster.local
{{ end }}
