bitwardenrs:
    fullnameOverride: "bitwarden"
    bitwardenrs:
        admin:
            enabled: false
    persistence:
        enabled: true
    podAnnotations:
        backup.velero.io/backup-volumes: bitwarden
