{{ if not .Values.installCSIDriver }}
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  labels: {{- include "synology-csi.labels" $ | nindent 4 }}
  name: csi.san.synology.com
spec:
  attachRequired: true # Indicates the driver requires an attach operation (TODO: ControllerPublishVolume should be implemented)
  podInfoOnMount: true
  fsGroupPolicy: File # The default in the chart doesn't chown correctly
  volumeLifecycleModes:
    - Persistent
{{ end }}
