# iscsiVolumes: []
# smbVolumes:
#  - name: my-volume
#    path: MiscFiles/some/path
# backupSchedules:
#   - name: my-backup
#     schedule: 0 2 * * 0
#     ttl: 336h0m0s
#traefikRoutes:
#  host.example.com:
#    serviceName: my-serviceName
#    servicePort: my-servicePort
#    #Optional: Override the auth settings
#    #auth:
#    #  domain: example.com
#    #  host: auth
#    #  realm: example.com
#    routes:
#    - path: /
#    - path: /login
#      auth: true
#    - path: /admin
#      auth: true
#      authGroups:
#        - admin
#        - superuser
#    - path: /old-path
#      redirectPath: /new-path
#    - pathPrefix: /docs
#      auth: true
# traefikRoute:
#   - serviceName: 
#     servicePort: 
#     host: 
#     path: (optional)
#     routeName: (optional)
#     https: false (optional)
#     #entryPoints: (optional)
#     #  - websecure
#     #whiteList: (optional, off)
#     #- 192.168.0.0/23
#     #- 10.244.0.0/16
#     #whiteListInternal: false (optoinal)
# traefikRouteTCP:
#   - serviceName: 
#     servicePort: 
#     entryPoints:
#       - <from traefik config> 
# keycloakClients:
#   myClient:
#     clientSecret:
#       # Name of the Kubernetes secret that holds the client secret (in keycloak namespace)
#       secretName: my-client-secret
#       # Key within the secret where the secret value is stored.
#       secretKey: clientSecretKey
#     # App host and domain to redirect after login (application using keycloak for users)
#     clientHost: app
#     clientDomain: example.com
#     # Auth host and domain for logout (keycloak itself)
#     keycloakHost: auth
#     keycloakDomain: example.com
#   anotherClient:
#     ...
