kube-prometheus-stack:
    fullnameOverride: "kps"

    defaultRules:
      rules:
        etcd: false
        kubeScheduler: false

    alertmanager:
      ingress:
        enabled: true
        annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
            traefik.ingress.kubernetes.io/router.middlewares: "traefik-local-ipwhitelist@kubernetescrd"
        paths:
            - /
   
    grafana:
        fullnameOverride: grafana
        adminPassword: prom-operator # change me?
        ingress:
          enabled: true
          annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
              traefik.ingress.kubernetes.io/router.middlewares: "traefik-local-ipwhitelist@kubernetescrd"
          path: /
        persistence:
          # type: pvc
          enabled: true
          # storageClassName: default
          accessModes:
            - ReadWriteOnce
          size: 10Gi
          # annotations: {}
          finalizers: []
          # subPath: ""
          # existingClaim:
    
    prometheus-node-exporter:
        fullnameOverride: node-exporter

    prometheus:
        ingress:
          enabled: true
          annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
              traefik.ingress.kubernetes.io/router.middlewares: "traefik-local-ipwhitelist@kubernetescrd"
          paths:
              - /
        prometheusSpec:
            ruleSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            storageSpec:
                volumeClaimTemplate:
                  spec:
                    #storageClassName: gluster
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 50Gi
                    #selector: {}

    kubelet:
      enabled: true
      namespace: llama

    prometheusOperator:
        kubeletService:
          namespace: llama

    kube-state-metrics:
        fullnameOverride: kube-state-metrics

    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeControllerManager:
      enabled: false
templates:
    prometheusRules: []
