{{- range $clientName, $clientConfig := .Values.client }}
---
apiVersion: keycloak.infra.doodle.com/v1beta1
kind: KeycloakClient
metadata:
  name: {{ $clientName }}
  namespace: keycloak
spec:
  client:
    clientId: {{ $clientName }}
    enabled: true
    clientAuthenticatorType: client-secret
    secret: ${secret:{{ $clientConfig.clientSecret.secretName }}:{{ $clientConfig.clientSecret.secretKey }}}
    redirectUris:
      - "https://{{ $clientConfig.redirectHost }}.{{ $clientConfig.redirectDomain }}/*"
    webOrigins:
      - "+"
    protocol: openid-connect
    attributes:
      backchannel.logout.session.required: "false"
      exclude.session.state.from.auth.response: "true"
      post.logout.redirect.uris: "https://{{ $clientConfig.redirectHost }}.{{ $clientConfig.redirectDomain }}/*"
      frontchannel.logout.url: "https://{{ $clientConfig.redirectHost }}.{{ $clientConfig.redirectDomain }}/oauth2/sign_out?rd=https%3A%2F%2F{{ $clientConfig.authHost}}.{{ $clientConfig.authDomain }}%2Frealms%2F{{ $clientConfig.authHost }}%2Faccount"
    bearerOnly: false
    consentRequired: false
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: false
    publicClient: false
    frontchannelLogout: true
    fullScopeAllowed: true
    nodeReRegistrationTimeout: -1
    defaultClientScopes:
      - "groups"
      - "profile"
      - "email"
      - "roles"
    optionalClientScopes:
      - "address"
      - "phone"
    access:
      view: true
      configure: true
      manage: true
{{- end }}
