keycloak:
  operator:
    image:
      repository: quay.io/keycloak/keycloak-operator
      tag: "25.0.6"  # Operator version
      pullPolicy: IfNotPresent
  replicaCount: 1
  # required
  host:
  domain:
  # Enable either test realm template
  #realms:
  #  test.realm: {}
  #realms:
  #  testRealm:
  #    clientRoles:
  #      testClient:
  #        - name: test
  #          description: description
  #    # Groups just accepts the upstream 'groups' format from the CRD directly
  #    groups:
  #      - name: testgroup
  #        clientRoles:
  #          testclient:
  #            - users
  #    users:
  #      - emailVerified: true
  #        enabled: true
  #        groups:
  #          - TestGroup
  #          - TestGroup/subGroup
  #        username: testUser
keycloak-controller:
  fullnameOverride: "keycloak-controller"
  # These look like they can just be updated with the chart version they are released together I think
  #image:
  #  repository: ghcr.io/doodlescheduling/keycloak-controller
  #  tag: v2.4.0


postgresql:
  storageSize: 10Gi
