keycloak:
  operator:
    image:
      repository: quay.io/keycloak/keycloak-operator
      tag: "25.0.5"  # Operator version
      pullPolicy: IfNotPresent
  image:
    repository: quay.io/keycloak/keycloak
    tag: "25.0.5"  # Keycloak version
  replicaCount: 1
  # required
  host:
  domain:

keycloak-controller:
  fullnameOverride: "keycloak-controller"
  # These look like they can just be updated with the chart version they are released together I think
  #image:
  #  repository: ghcr.io/doodlescheduling/keycloak-controller
  #  tag: v2.4.0


postgresql:
  storageSize: 10Gi
