operator:
  image:
    repository: quay.io/keycloak/keycloak-operator 
    pullPolicy: IfNotPresent
    tag: "14.0.0"
keycloak:
  ingress:
    enabled: False
    host: keycloak.in.lab
ingress:
  enabled: True
  hosts: 
    - keycloak.in.lab
  path: /
