---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-oauth2-proxy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      #istio: ingressgateway
      app.kubernetes.io/name: gollum
  jwtRules:
  - issuer: "https://dex.in.lab"
    jwksUri: "http://dex.in.lab/keys"
    forwardOriginalToken: true
