---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-dex
  namespace: istio-system
spec:
  #selector:
  #  matchLabels:
  #    #istio: ingressgateway
  #    app.kubernetes.io/name: gollum
  jwtRules:
  - issuer: "https://dex.in.lab"
    #jwksUri: "https://dex.in.lab/keys"
    jwksUri: "http://dex.in.lab/keys"  # Istio fails with self-signed endpoint
    forwardOriginalToken: true
