---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-self-signed
spec:
  # isCA: true
  commonName: istio-system
  secretName: istio-default-cert
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
