{{ range .Values.istioTemplates.strictNamespaces }}
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "default"
  namespace: {{ . }}
spec:
  mtls:
    mode: STRICT
{{ end }}
