apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: sealed-secrets
    namespace: argocd
spec:
    destination:
        namespace: sealed-secrets
        server: https://kubernetes.default.svc
    project: default
    source:
        path: sealed-secrets
        targetRevison: HEAD
        helm:
            valuesfiles:
                - values.yaml
        repoURL: https://github.com/chris-sanders/argocd.git
    syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
