certs:
  selfSigned: true
  installProduction: false
  installStaging: false
  dnsNames: []
traefik:
  service:
    type: LoadBalancer
    spec:
      externalTrafficPolicy: Local
  ports:
    web:
      redirectTo:
        port: websecure
  tlsStore:
    default:
      certificates:
        - secretName: traefik-cert
      defaultCertificate:
        secretName: traefik-cert
