dashboard: {}
traefik:
    ports:
        udp53:
            exposedPort: 53
            port: 5300
            expose: true
            protocol: UDP
    globalArguments:
        - "--global.checknewversion"
        - "--serversTransport.insecureSkipVerify=true"
    service:
        spec:
            externalTrafficPolicy: Local
    ingressRoute:
        dashboard:
            enabled: false
