traefik:
    service:
      # enabled: true
      # type: LoadBalancer
      # # Additional annotations (e.g. for cloud provider specific config)
      # annotations: {}
      # # Additional entries here will be added to the service spec. Cannot contains
      # # type, selector or ports entries.
      spec:
        # loadBalancerIP: "10.0.9.1"
        # clusterIP: "2.3.4.5"
      #loadBalancerSourceRanges: []
      #  # - 192.168.0.1/32
      #  # - 172.16.0.0/16
      #externalIPs:
      #  - 10.0.9.1
      #  - 10.0.9.2
    ports:
        udp19132:
            exposedPort: 19132
            port: 19132
            expose: true
            protocol: UDP

templates:
    dashboard_hostname: "traefik.in.lab"
    #dashboard_auth: "lab"
    #default_cert: "traefik-cert"
