certs:
  selfSigned: true
  installProduction: false
  installStaging: false
  dnsNames: []
traefik:
  service:
    type: LoadBalancer
    # Disable until cilium supports advertising from local
    #spec:
    #  externalTrafficPolicy: Local
  ports:
    web:
      redirectTo:
        port: websecure
  tlsStore:
    default:
      certificates:
        - secretName: traefik-self-signed
      defaultCertificate:
        secretName: traefik-self-signed
local:
  ciliumPolicy:
    enable: true
