certs:
  selfSigned: true
  installProduction: false
  installStaging: false
  dnsNames: []
traefik:
  service:
    type: LoadBalancer
    # Disable until cilium supports advertising from local
    #spec:
    #  externalTrafficPolicy: Local
  ports:
    web:
      redirectTo:
        port: websecure
  experimental:
    plugins:
      jwt:
        moduleName: github.com/traefik-plugins/traefik-jwt-plugin
        version: v0.9.0
  tlsStore:
    default:
      certificates:
        - secretName: traefik-self-signed
      defaultCertificate:
        secretName: traefik-self-signed
local:
  ciliumPolicy:
    enable: true
