{{- if .Values.templates.letsencrypt.staging }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: {{ .Values.templates.letsencrypt.email }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    - dns01:
        cnameStrategy: Follow
        acmeDNS:
          host: {{ .Values.templates.letsencrypt.acme_host }}
          accountSecretRef:
              name: acme-dns
              key: acmedns.json
{{- end }}
{{- if .Values.templates.letsencrypt.production }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: {{ .Values.templates.letsencrypt.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production-account-key
    solvers:
    - dns01:
        cnameStrategy: Follow
        acmeDNS:
          host: {{ .Values.templates.letsencrypt.acme_host }}
          accountSecretRef:
              name: acme-dns
              key: acmedns.json
{{- end }}
