{{- if eq .Values.templates.secrets "lab" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: acme-dns
  namespace: cert-manager
spec:
  encryptedData:
    acmedns.json: AgBelYqh3+6gffwzzuEtLB8CtEAYHzwYeGu1/DeEGdEAAMOQn/kPR6l+WkeN+34abd9n5YQkCgJekgarW5cRvorMY7wAEwPPPlb9eUrWZHvtWMWrijuNHaNz/ZaKqMV7/bahqdVzVuHXHbA2Vh4cjK9+Nuy7/3kvrdz/2YknO0c1HsZbLSpzy2CuTRfE99jiCG4Etyybx62T0bCMJRs2Zp9xfFXOn5m+1M0YlTppLLUheWvroT6U3Gz3d4cXmXMUffJNtUL2KjgX3TKfgjbUyLtZCBj1AYg7wA7jzc9P4iAGTYkh016e13af0yN6GRTkSuz5swN4bC5tpLuOoBjC+KFNTRznJEgMx7KolRtLRyT7ct88d3O3/HXx81T7WRdn8Ju0K/ugyl4vx7QFmtOVwTC5+4fB6cigyH9WDvBCiLq9VDSsmyN1unFYEVPhkSnQmuutSVIKrZx72CZNgDa7Nyy/aty9nwGMX6TN4UMlkC4oFU6gC+aPqa67jC/1glhpbFy1I/9wWOu6dQz/0ECXt0zFvmBWO53kre/J6ULVpv0C3nK/ZdqWyddXzrdSs0522UZADdsCazrHCygYrXi8MnIOTa0M0qMQpK3p2Ll6ocDKeAN8zyT4ChgNFm1jp17Da+zCupmp5W+AHsNCGLpUyVG2R2qmACcfiAMrcXOL5iJ62YNRUaj3/CFj+xEJHc9v/FNm0EEL1JaBIYCYoy4s6NIa8uqVywyZj0nF0qrlsPzurkzih/BxxDEtSsBgbJTSr5OhG5xyMf358+T1eQzqFo0x7DnDg0HTpW77oNQ7qTSRbk8XKmChZMRNegDK8ZUXZ79veyHPfJfdplQiHPIynVL/xkzLCaNpepE3JNArFDL1T2oonjGcz64zVocolqv1En4ViH8zilpY/AbXOWhAuAKMt1L55Oxo0M06yEJwaBkGLDY1ZkCgDWN8WfPg0feEbw0ZmIb+xSH1l7vEwMvak6HCtug/x4QG2afFSsNVdLDE6RXYUUWXN8xmLlU=
  template:
    metadata:
      creationTimestamp: null
      name: acme-dns
      namespace: cert-manager
    type: Opaque
{{- end }}
