nextcloud:
#  image:
#    tag: 30.0.2-apache
  nextcloud:
    host: nextcloud.192.168.121.193.nip.io
    username: admin
    password: password
    extraEnv:
      - name: TRUSTED_PROXIES
        value: "10.244.0.0/16"
      - name: OVERWRITEPROTOCOL
        value: "https"
    configs:
      extra.config.php: |-
        <?php
        $CONFIG = array (
          'maintenance_window_start' => 1
        );
  livenessProbe:
    initialDelaySeconds: 100
    periodSeconds: 100
    timeoutSeconds: 50
    failureThreshold: 30
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 100
    periodSeconds: 100
    timeoutSeconds: 50
    failureThreshold: 30
    successThreshold: 1
  startupProbe:
    enabled: false
    initialDelaySeconds: 300
    periodSeconds: 100
    timeoutSeconds: 50
    failureThreshold: 30
    successThreshold: 1
  internalDatabase.enabled: false
  externalDatabase:
    enabled: true
    type: postgresql
    host: "postgres-service:5432"
    database: nextcloud
    username: nextcloud
    password: password
  postgresql:
    enabled: true
    global:
      postgresql:
        auth:
          username: nextcloud
          password: password
          database: nextcloud
