nextcloud:
#  image:
#    tag: 30.0.2-apache
  nextcloud:
    host: nextcloud.192.168.121.193.nip.io
    username: admin
    password: password
    extraEnv:
      - name: TRUSTED_PROXIES
        value: "10.244.0.0/16"
      - name: OVERWRITEPROTOCOL
        value: "https"
    configs:
      extra.config.php: |-
        <?php
        $CONFIG = array (
          'maintenance_window_start' => 1
        );
  initContainers:
    - name: occ-commands
      image: "{{ .Values.nextcloud.image.repository }}:{{ .Values.nextcloud.image.tag }}"
      command: ["sh", "-c"]
      args:
        - >
          php /var/www/html/occ maintenance:repair --include-expensive &&
          php /var/www/html/occ db:add-missing-indices;
      volumeMounts:
        - name: nextcloud-data
          mountPath: /var/www/html
  cronjob:
    enabled: true
  livenessProbe:
    initialDelaySeconds: 100
    periodSeconds: 100
    timeoutSeconds: 50
    failureThreshold: 30
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 100
    periodSeconds: 100
    timeoutSeconds: 50
    failureThreshold: 30
    successThreshold: 1
  startupProbe:
    enabled: false
    initialDelaySeconds: 300
    periodSeconds: 100
    timeoutSeconds: 50
    failureThreshold: 30
    successThreshold: 1
  internalDatabase:
    enabled: false
    name: nextcloud
  externalDatabase:
    enabled: true
    type: postgresql
    database: nextcloud
    username: nextcloud
    password: password
  postgresql:
    enabled: true
    global:
      postgresql:
        auth:
          username: nextcloud
          password: password
          database: nextcloud
