{{ if .Values.certs.selfSigned }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-self-signed
  argocd.argoproj.io/sync-wave: "-1"
spec:
  commonName: traefik
  secretName: traefik-self-signed
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}
{{- if .Values.certs.installProduction }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert
  argocd.argoproj.io/sync-wave: "-1"
spec:
  secretName: traefik-cert
  duration: 2160h0m0s
  renewBefore: 720h0m0s
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
  - server auth
  - client auth
  dnsNames:
  {{- range .Values.certs.dnsNames }}
  - {{ . | quote }}
  {{- end }}
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
{{- end }}
{{- if .Values.certs.installStaging }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert-staging
  argocd.argoproj.io/sync-wave: "-1"
spec:
  secretName: traefik-cert-staging
  duration: 2160h0m0s
  renewBefore: 720h0m0s
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
  - server auth
  - client auth
  dnsNames:
  {{- range .Values.certs.dnsNames }}
  - {{ . | quote }}
  {{- end }}
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
{{- end }}
