woodpecker:
  agent:
    # -- Enable the agent component
    enabled: true
    replicaCount: 1
    image:
      registry: docker.io
      repository: woodpeckerci/woodpecker-agent
      tag: 'v3.7.0'
      pullPolicy: IfNotPresent
  
    env:
      WOODPECKER_BACKEND_K8S_STORAGE_RWX: false
  
    # -- Add extra secret that is contains environment variables
    extraSecretNamesForEnvFrom:
      - woodpecker-config

    # Don't create the default empty secret
    secrets: []

    podSecurityContext:
      runAsUser: 1000
      fsGroup: 1000
      runAsNonRoot: true
 
    # -- Add security context
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
  
  server:
    enabled: true
 
    image:
      registry: docker.io
      repository: woodpeckerci/woodpecker-server
      tag: 'v3.7.0'
      pullPolicy: IfNotPresent
  
    env:
      WOODPECKER_EXPERT_WEBHOOK_HOST: 'http://woodpecker-server.woodpecker.svc'
      WOODPECKER_OPEN: true
      WOODPECKER_GITEA: true
      WOODPECKER_GITEA_URL: 'http://gitea-http.gitea.svc:3000'
      #WOODPECKER_ADMIN:
      #WOODPECKER_HOST: 
      #WOODPECKER_DEV_GITEA_OAUTH_URL:
  
    # Don't create the default empty secret
    secrets: []
    # -- Add extra environment variables from the secrets list
    extraSecretNamesForEnvFrom:
      - woodpecker-config

    podSecurityContext:
      runAsUser: 1000
      fsGroup: 1000
      runAsNonRoot: true
 
    # -- Add security context
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
