woodpecker:
  agent:
    # -- Enable the agent component
    enabled: true
    replicaCount: 1
    image:
      registry: docker.io
      repository: woodpeckerci/woodpecker-agent
      tag: 'v2.7.3'
      pullPolicy: IfNotPresent
  
    env:
      WOODPECKER_BACKEND_K8S_STORAGE_RWX: false
  
    # -- Add extra secret that is contains environment variables
    extraSecretNamesForEnvFrom:
      - woodpecker-config

    # Don't create the default empty secret
    secrets: []
  
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
  
  server:
    enabled: true
 
    image:
      registry: docker.io
      repository: woodpeckerci/woodpecker-server
      tag: 'v2.7.3'
      pullPolicy: IfNotPresent
  
    env:
      WOODPECKER_WEBHOOK_HOST: 'http://woodpecker-server.woodpecker.svc'
      WOODPECKER_OPEN: true
      WOODPECKER_GITEA: true
      WOODPECKER_GITEA_URL: 'http://gitea-http.gitea.svc:3000'
      #WOODPECKER_ADMIN:
      #WOODPECKER_HOST: 
      #WOODPECKER_DEV_GITEA_OAUTH_URL:
  
    # Don't create the default empty secret
    secrets: []
    # -- Add extra environment variables from the secrets list
    extraSecretNamesForEnvFrom:
      - woodpecker-config
 
    # -- Add security context
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
