---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name | quote }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      containers:
      - image: joohoi/acme-dns:latest
        name: acmedns
        ports:
        - containerPort: 443
        - containerPort: 53
        - containerPort: 53
          protocol: UDP
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /etc/acme-dns
          name: acmedns-claim0
          readOnly: true
        - mountPath: /var/lib/acme-dns
          name: acmedns-claim1
      restartPolicy: Always
      volumes:
      - name: acmedns-claim0
        configMap:
          name: acme-dns-config
      - name: acmedns-claim1
        persistentVolumeClaim:
          claimName: acmedns-pvc
