---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | quote }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
spec:
  ports:
  - name: "443"
    port: 443
    targetPort: 443
  - name: "53"
    port: 53
    targetPort: 53
  - name: 53-udp
    port: 53
    protocol: UDP
    targetPort: 53
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
status:
  loadBalancer: {}
