apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: base
    namespace: argocd
spec:
    destination:
        namespace: argocd
        server: https://kubernetes.default.svc
    project: default
    source:
        path: apps/base
        targetRevision: HEAD
        helm:
            valueFiles:
                - values.yaml
        repoURL: https://github.com/chris-sanders/argocd.git
    syncPolicy:
        automated:
            prune: true
        syncOptions:
          - CreateNamespace=true
