name: istio
version: 1.0.0
appVersion: 1.9.5
apiVersion: v2
dependencies:
    - name: base
      version: '^1.10.0'
      repository: file://./istio-1.10.0/manifests/charts/base/
    - name: istio-discovery
      version: '^1.10.0'
      repository: file://./istio-1.10.0/manifests/charts/istio-control/istio-discovery/
    - name: istio-cni
      version: '^1.10.0'
      repository: file://./istio-1.10.0/manifests/charts/istio-cni/
    - name: istio-ingress
      version: '^1.10.0'
      repository: file://./istio-1.10.0/manifests/charts/gateways/istio-ingress/
    #- name: kiali-operator
    #  version: '^1.35.0'
    #  repository: https://kiali.org/helm-charts
