istioTemplates:
  jwtIssuer: "https://keycloak.in.lab/auth/realms/home"
  # http for lab, use https when a proper TLS is available
  jwksUri: "http://keycloak.in.lab/auth/realms/home/protocol/openid-connect/certs"
  credentialName: istio-default-cert # must be the same as secret
  apps:
  - bitwarden-lab
  - gollum-lab
  - oauth-lab
  - keycloak-lab
  strictNamespaces:
  - oauth2-proxy
  - gollum
  - keycloak
