istioTemplates:
  jwtIssuer: "https://keycloak.in.lab/auth/realms/basic"
  jwksUri: "http://keycloak.in.lab/auth/realms/basic/protocol/openid-connect/certs"
  credentialName: istio-default-cert # must be the same as secret
  apps:
  - bitwarden-lab
  - gollum-lab
  #- dex-lab
  - oauth-lab
  strictNamespaces:
  - oauth2-proxy
  #- dex
  - gollum
