mutltus:
  #image:
  #   repository: ghcr.io/k8snetworkplumbingwg/multus-cni
  #   tag: v4.0.1-thick
  cni:
    #image:
    #  repository: ghcr.io/angelnu/cni-plugins
    #  tag: 1.3.0
    paths:
      config: /etc/cni/net.d
      bin: /opt/cni/bin
  #resources:
  #  requests:
  #    cpu: 5m
  #    memory: 70M
  #  limits:
  #    memory: 150M

  hostPaths:
    netns: /var/run/netns
