velero:
    configuration:
        provider: aws
        backupStorageLocation:
            name: default
            bucket: default
            # bucket: Required
    #        config:
    #            region: backblaze
    #            s3ForcePathStyle: true
    #            s3Url: https://s3.us-west-001.backblazeb2.com
    #credentials:
    #    existingSecret: velero-backblaze
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.1.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /target
        name: plugins
    snapshotsEnabled: false
    deployRestic: true
    restic:
        podVolumePath: /var/snap/microk8s/common/var/lib/kubelet/pods
        privileged: false
