apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
   app: keycloak
spec:
  instances: 1
  externalAccess:
    enabled: {{ .Values.keycloak.ingress.enabled }}
    host: {{ .Values.keycloak.ingress.host }}
  extensions:
  - https://github.com/wadahiro/keycloak-discord/releases/download/v0.3.1/keycloak-discord-ear-0.3.1.ear
