apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: test
  labels:
    app: keycloak-basic
spec:
  realm:
    id: "basic"
    realm: "basic"
    enabled: True
    displayName: "Test Realm"
  instanceSelector:
    matchLabels:
      app: keycloak
