labels:
  backend: kubernetes

when:
  - event: pull_request

steps:
  - name: debug-env-vars
    image: alpine:latest
    commands:
      - echo "=== User info ==="
      - id
      - echo "=== All Environment Variables ==="
      - env | sort
