
# Only run pipeline when values.yaml files are changed
when:
  event: [pull_request]
  path:
    include: ["*/values.yaml"]

labels:
  backend: local

steps:
  detect-changes:
    image: /usr/bin/bash
    commands:
      - |
        echo "Detecting changes in values.yaml files..."
        
        # Debug: Print the CI_PIPELINE_FILES content
        echo "CI_PIPELINE_FILES content:"
        echo "$CI_PIPELINE_FILES"
        
        # Use jq to find */values.yaml files and extract directory names
        if [ -n "$CI_PIPELINE_FILES" ]; then
          echo "$CI_PIPELINE_FILES" | jq -r '.[] | select(test("^[^/]+/values.yaml$")) | split("/")[0]' > /tmp/changed_software.txt
        else
          echo "CI_PIPELINE_FILES is empty or not set"
          touch /tmp/changed_software.txt
        fi

        # TEMPORARY: Remove woodpecker from the list for testing
        grep -v "^woodpecker$" /tmp/changed_software.txt > /tmp/changed_software_filtered.txt
        mv /tmp/changed_software_filtered.txt /tmp/changed_software.txt
        
        if [ ! -s /tmp/changed_software.txt ]; then
          echo "No matching values.yaml files were changed. Skipping tests."
        else
          echo "Software with changed values.yaml files:"
          cat /tmp/changed_software.txt
        fi

  #run-base-tests:
  #  image: bash:latest
  #  commands:
  #    - |
  #      if [ ! -f /tmp/changed_software.txt ]; then
  #        echo "No changes detected. Skipping tests."
  #        exit 0
  #      fi
  #      
  #      # Process each software name
  #      cat /tmp/changed_software.txt | while read -r SOFTWARE_NAME; do
  #        echo "Testing software: $SOFTWARE_NAME"
  #        
  #        # Clone the corresponding k8s repository
  #        git clone "https://github.com/your-org/k8s.${SOFTWARE_NAME}.git" "/tmp/k8s.${SOFTWARE_NAME}"
  #        cd "/tmp/k8s.${SOFTWARE_NAME}"
  #        
  #        # Run initial molecule tests
  #        echo "Running initial molecule tests for $SOFTWARE_NAME..."
  #        # Assuming molecule is installed or using a container with molecule
  #        molecule test -s default
  #        
  #        # Save the exit status for the next step
  #        echo "$?" > "/tmp/${SOFTWARE_NAME}_base_test_status.txt"
  #      done

  #run-upgrade-tests:
  #  image: bash:latest
  #  commands:
  #    - |
  #      if [ ! -f /tmp/changed_software.txt ]; then
  #        echo "No changes detected. Skipping upgrade tests."
  #        exit 0
  #      fi
  #      
  #      # Process each software name
  #      cat /tmp/changed_software.txt | while read -r SOFTWARE_NAME; do
  #        echo "Running upgrade tests for software: $SOFTWARE_NAME"
  #        
  #        # Check if base tests passed
  #        if [ -f "/tmp/${SOFTWARE_NAME}_base_test_status.txt" ] && [ "$(cat "/tmp/${SOFTWARE_NAME}_base_test_status.txt")" != "0" ]; then
  #          echo "Base tests failed for $SOFTWARE_NAME. Skipping upgrade tests."
  #          continue
  #        fi
  #        
  #        cd "/tmp/k8s.${SOFTWARE_NAME}"
  #        
  #        # Modify molecule variables to target the PR branch
  #        echo "Updating molecule variables to target PR branch..."
  #        # Example of modifying molecule.yml or group_vars to target PR branch
  #        # This will depend on your molecule setup
  #        sed -i "s/target_branch: main/target_branch: $CI_COMMIT_BRANCH/" molecule/default/molecule.yml
  #        
  #        # Run molecule tests again for upgrade validation
  #        echo "Running upgrade tests for $SOFTWARE_NAME..."
  #        molecule test -s default --destroy=never
  #      done

