{{- if .Values.bitwardenrs.domain }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-tls-bitwarden
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`{{ .Values.bitwardenrs.domain }}`)
    kind: Rule
    services:
    - name: bitwardenrs
      port: 80
      namespace: bitwardenrs
  tls:
      store:
          name: default
{{- end }}
