apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: kube-prometheus-stack
    namespace: argocd
spec:
    destination:
        namespace: llama
        server: https://kubernetes.default.svc
    project: default
    source:
        path: llama/kube-prometheus-stack
        targetRevision: HEAD
        helm:
            valueFiles:
                - values.yaml
                - values-lab.yaml
        repoURL: https://github.com/chris-sanders/argocd.git
    syncPolicy:
        automated:
            prune: true
        syncOptions:
          - CreateNamespace=true
