apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: radarr
    namespace: argocd
spec:
    destination:
        namespace: usenet
        server: https://kubernetes.default.svc
    project: default
    source:
        path: usenet/radarr
        targetRevision: HEAD
        helm:
            valueFiles:
                - values.yaml
                - values-lab.yaml
        repoURL: https://github.com/chris-sanders/argocd.git
    syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
