{{- $keycloakVersion := regexFind "^[0-9]+" .Values.keycloak.image.tag }}
{{- range $realmName, $realmConfig := .Values.keycloak.realms }}
---
apiVersion: keycloak.infra.doodle.com/v1beta1
kind: KeycloakRealm
metadata:
  name: {{ $realmName | lower }}
  namespace: {{ $.Release.Namespace }}
spec:
  version: {{ $keycloakVersion | quote }}
  address: http://keycloak-service.{{ $.Release.Namespace }}.svc:8080/
  authSecret:
    name: keycloak-initial-admin
  interval: 1h
  timeout: 5m0s
  resourceSelector:
    matchLabels: {}
  realm:
    enabled: true
    displayName: {{ $realmName | title }}
    duplicateEmailsAllowed: false
    editUsernameAllowed: false
    clientScopes:
      - name: groups
        description: "Users keycloak groups"
        protocol: openid-connect
        attributes:
          include.in.token.scope: "true"
          display.on.consent.screen: "false"
        protocolMappers:
          - name: groups
            protocol: openid-connect
            protocolMapper: oidc-group-membership-mapper
            config:
              full.path: "false"
              introspection.token.claim: "true"
              userinfo.token.claim: "true"
              multivalued: "true"
              id.token.claim: "true"
              lightweight.claim: "false"
              access.token.claim: "true"
              claim.name: "groups"
    defaultDefaultClientScopes:
      - profile
      - email
      - groups
{{- end }}
