{{- if eq .Values.templates.secrets "lab" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-backblaze
  namespace: velero
spec:
  encryptedData:
    cloud: AgBXWxrUJVSg97AhgnfFUtWYEC3W0wToHf6OdhLo72i1nv6uO4m+t27px+p6TLQ0UvvXxYRjE07i8HQPg9QagDiXtRrlWNsoxm4xggfUIkZdH6Yyve94YWt0cU11oPiF51g9ZcHdFxN9z15R+PxZY6qEukX/GTj/69/ABJmoMPJUk8C1dB0PB4Ly0hj9IWysJKYFQE0Q8RsL3VGNx4FKrt3LFnzUfP4M3XS2K1ShgDJD+ATrs8BFwCDp1z+ppyocpbDwBmaoYKv7PSxnOnfSnwTua1t3BomAQen+rfS9PXkOfTOZsGeQilFV9CnGvOUUIiVVOtcG4riffDsfWO9hIGJH210fVTVdeErzOwqqckTK4EnH4N3bJUjMi9DoGYiXZJ8o5LCIAqnQwA6w0uvp3/Ump7YlRVYMF4noCF5tI1wmW6JKjz1VVj2Y/8oe3lbR7a9PCNLoiTkmRbR1B/jzrL5zVmBJ+Y3Nfnwe63erhhOOSM41AgxaEG8zfg/hCK+qmiJVaNDQiB/0gHHLCbM6W3yzQWpJNiMI5sy3bnzwHWDVHcnOdTlPp8iLNMeUAV9O0E4hUSgw2DuqIPhdaVxl8BvtyOC+xwwMT4mPR0gK5q8rRekxk4RNvcCT/mCm4Nj6b+9KJd1F7nxhpPSTAP2ARl1alg/F52H7NK1yc7DRIkiIORQJhTIgNYkqHgsa1GEIX2qU3tdjAt6LLZUSlTRmVKIgBc7ZmD/gh0ni8DLLoOpP0OcyPEqiOlPzCG3UyQlHtRquJqEH4GWiymWZWM9avu6M70n+76FAZn3FTNffmMG7Atsiy0gLYgfFiucOk97f+AI3z8qXW0IjOcJreXYK8Y7iSw==
  template:
    metadata:
      creationTimestamp: null
      name: velero-backblaze
      namespace: velero
{{- end }}
