{{- if eq .Values.templates.secrets "lab" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-restic-credentials
  namespace: velero
spec:
  encryptedData:
    repository-password: AgAuv6TSAUS4Y8y1pyZiKtxQ8gqzZUUDR4PVQy3V+QeMxsPaLgLQm85Umz37ooBNTZC1zk+ExLXgC2iWRldPXRFMqibj9tGz8qdve+wMaLFXTqoHvcJlgLOkpXsO5xBCBlm3tO2m5CqQ1371LoqqouXVhWixg8b8bCKv1oGyO2CBtBjdDIKSOhnGretQYUc8sq5lSPLkba7JE+iNzonmoGnoRpm5oAjWuC5F398UPBy3LSMw+D2b++Et9tY2tk2spnzdo2fLYrT4KHBGgIwjdat+S1nCEzKc/ucJnRpkhqrH1z1AoyXPnVWd3WVBfV3O4WAngLE9ff93FhxtblPn4TcShxjstZjhNFuVk/m1c7vFIt5ueW6cGQiN8OKo1i73FP8U9V9dIMYBxfGVNcYX/n0vsIP1HqxTyXnGCFJuWeGN/HgaIszUao9AZhjYPU6X/Q3nup80PQNApR4CRP+8yFxgf8R3jE3a2wG/U58Tx6L5PWbXL2sLL/x/aaD18ofIKLEcyOVPhGMdtaBhtKk0R9qMkw+H9ShQp8XOo3RCDJCzvatO/iaaQnoyWum/rmwk3bgP/j11JIqSH2y/+fjs4PBvZ3C3J3+72qGI1F9v0kQ16drnLh6dkYr+ixLgGSd0jJ+i/YVeoYy3RuS7GNM2oSMFiAo9BIKlrQb1zdcGvO2v2eQAig9SKPTAibipgPIwUR9DBgEUhMEECanQEWz7LSKPKut1FpBYKehfYaUTdEsrjPf/Zn+/jmq4H3G1kg3OHHo=
  template:
    metadata:
      creationTimestamp: null
      name: velero-restic-credentials
      namespace: velero
{{- end }}
